# Generated by Django 4.2.5 on 2023-10-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to='', verbose_name='Фотография 1 (обязательно)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография 2 (необязательно)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография 3 (необязательно)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фотография 4 (необязательно)'),
        ),
    ]
